name: SonarCloud Analysis

on:
  push:
    branches:
      - master  # o 'main' si es tu rama principal
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # necesario para SonarCloud

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          pip install sonar-scanner
          sonar-scanner \
            -Dsonar.projectKey=ChristianHernandez7_search_engine_backend \
            -Dsonar.organization=christianhernandez7 \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.python.coverage.reportPaths=coverage.xml \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

